services:
    leenoz.zeina.controller.acp:
        class: leenoz\zeina\controller\acp_controller
        arguments:
            - '@config_text'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'

    leenoz.zeina.listener:
        class: leenoz\zeina\event\main_listener
        arguments:
            - '@config'
            - '@config_text'
            - '@template'
        tags:
            - { name: event.listener }